# Generated by Django 5.0.4 on 2024-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_archive_user_rentbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbook',
            name='rent_statu',
            field=models.BooleanField(default='', max_length=200, verbose_name=True),
        ),
    ]
